### ISSUE TITLE
Documentation Issue for api.device_templates.DeviceTemplates.attach_to_template

### ISSUE THREAD

**Issue by rosia** [CiscoDevNet/python-viptela#103]
The docs say only three Args are required but what works is 5 args. see attached screenshot of the working one. 
![Screen Shot 2021-03-12 at 7 55 05 pm](https://user-images.githubusercontent.com/10355777/110917968-a6063d00-836e-11eb-9bdd-f7f02ae9a8aa.png)

**Comment by mtarking** [comment]
This issue seems resolved.

<img width="698" alt="Screen Shot 2021-08-06 at 6 23 46 PM" src="https://user-images.githubusercontent.com/18662173/128576632-b17a6719-4419-47f9-9a91-5e9deac03089.png">

<img width="684" alt="Screen Shot 2021-08-06 at 6 23 56 PM" src="https://user-images.githubusercontent.com/18662173/128576637-7e940330-b49b-4049-80e6-411866f41da1.png">
